# Generated by Django 4.2.30 on 2026-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0003_add_missing_fields_to_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='cliente_rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
