# Generated by Django 4.2.30 on 2026-06-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0003_cliente_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='incluye_iva',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.IntegerField(default=0)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contratistas.cotizacion')),
            ],
        ),
    ]
