# Generated by Django 4.2.30 on 2026-06-14 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0004_trabajo_incluye_iva_itemcotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='incluye_iva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
