# Generated by Django 4.2.30 on 2026-06-15 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratistas', '0005_cotizacion_incluye_iva_cotizacion_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='comuna',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contratista',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contratista',
            name='experiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contratista',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratista',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='contratistas.contratista')),
            ],
        ),
    ]
