# Generated by Django 4.2.30 on 2026-06-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0006_add_tipo_documento'),
    ]

    operations = [
    ]
