# Generated by Django 4.2.30 on 2026-06-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0006_contratista_comuna_contratista_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
