# Generated by Django 4.2.30 on 2026-06-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0007_add_tipo_documento'),
    ]

    operations = [
    ]
