# Generated by Django 4.2.30 on 2026-06-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0007_solicitudcotizacion_email_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='descartada',
            field=models.BooleanField(default=False),
        ),
    ]
