# Generated by Django 4.2.30 on 2026-06-18 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0008_solicitudcotizacion_descartada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('comentario', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='contratistas.contratista')),
                ('trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resena', to='contratistas.trabajo')),
            ],
        ),
    ]
