# Generated by Django 4.2.30 on 2026-06-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0008_add_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_impuesto',
            field=models.CharField(choices=[('ninguno', 'Sin impuesto'), ('iva', 'IVA 19%'), ('honorarios', 'Retención 15,25%')], default='ninguno', max_length=20),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tipo_impuesto',
            field=models.CharField(choices=[('ninguno', 'Sin impuesto'), ('iva', 'IVA 19%'), ('honorarios', 'Retención 15,25%')], default='ninguno', max_length=20),
        ),
    ]
