# Generated by Django 4.2.30 on 2026-06-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0009_remove_cotizacion_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='foto_url',
            field=models.URLField(blank=True, help_text='URL de la foto de perfil en Cloudinary', null=True),
        ),
    ]
