# Generated by Django 4.2.30 on 2026-07-01 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratistas', '0011_add_account_deactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratista',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo_impuesto',
            field=models.CharField(choices=[('ninguno', 'Exento impuesto'), ('iva', 'IVA 19%'), ('honorarios', 'Retención 15,25%')], default='ninguno', max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='tipo_impuesto',
            field=models.CharField(choices=[('ninguno', 'Exento impuesto'), ('iva', 'IVA 19%'), ('honorarios', 'Retención 15,25%')], default='ninguno', max_length=20),
        ),
        migrations.CreateModel(
            name='ReactivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
