# Generated by Django 4.2.30 on 2026-06-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0011_fix_token_resena_duplicados'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='comunas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
