# Generated by Django 4.2.30 on 2026-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0012_contratista_comunas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='oficios',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
