# Generated by Django 4.2.30 on 2026-06-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0015_contratista_email_verificado_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='rut',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
