# Generated by Django 4.2.30 on 2026-06-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0016_contratista_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='certificacion',
            field=models.TextField(blank=True),
        ),
    ]
