# Generated by Django 4.2.30 on 2026-06-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0018_alter_contratista_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratista',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
